name: 'Mirror image'
on:
  push:
    tags:
    - v*
jobs:
  build_apiserver:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF##*/}
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Log in to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to registries
      uses: docker/build-push-action@v2
      with:
        context: kube-apiserver
        push: true
        tags: |
          quay.io/mk8s/kube-apiserver:${{ steps.vars.outputs.tag }}
          hyperk8s/kube-apiserver:${{ steps.vars.outputs.tag }}

  build_controller_manager:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF##*/}
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Log in to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to registries
      uses: docker/build-push-action@v2
      with:
        context: kube-controller-manager
        push: true
        tags: |
          quay.io/mk8s/kube-controller-manager:${{ steps.vars.outputs.tag }}
          hyperk8s/kube-controller-manager:${{ steps.vars.outputs.tag }}

  build_scheduler:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF##*/}
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Log in to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to registries
      uses: docker/build-push-action@v2
      with:
        context: kube-scheduler
        push: true
        tags: |
          quay.io/mk8s/kube-scheduler:${{ steps.vars.outputs.tag }}
          hyperk8s/kube-scheduler:${{ steps.vars.outputs.tag }}

  build_proxy:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF##*/}
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Log in to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to registries
      uses: docker/build-push-action@v2
      with:
        context: kube-proxy
        push: true
        tags: |
          quay.io/mk8s/kube-proxy:${{ steps.vars.outputs.tag }}
          hyperk8s/kube-proxy:${{ steps.vars.outputs.tag }}
